-- Windows: PxrJSON.dll     Linux: libPxrJSON.so
-- Place in Firebird/plugins/udr/; bitness must match the server (x64).
-- EXTERNAL NAME 'PxrJSON!...' is the same on both OS.

set term ^ ;

create or alter package SJSON
as
begin
  function NEW_OBJECT() returns VARCHAR(8191) CHARACTER SET UTF8;
  function NEW_ARRAY() returns VARCHAR(8191) CHARACTER SET UTF8;
  function NEW_OBJKEY() returns CHAR(36) CHARACTER SET ASCII;
  function NEW_ARRKEY() returns CHAR(36) CHARACTER SET ASCII;
  function TOJSON(
      A_JSON    VARCHAR(8191) CHARACTER SET UTF8,
      A_COMPACT SMALLINT DEFAULT 1)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function KEYSIZE(
      A_JSON    VARCHAR(8191) CHARACTER SET UTF8,
      A_COMPACT SMALLINT DEFAULT 1)
    returns INTEGER;
  function PARSE(A_JSON VARCHAR(8191) CHARACTER SET UTF8)
    returns CHAR(36) CHARACTER SET ASCII;
  function CLONE(A_JSON VARCHAR(8191) CHARACTER SET UTF8)
    returns CHAR(36) CHARACTER SET ASCII;
  function EXTRACTJSON(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function EXTRACTKEY(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns CHAR(36) CHARACTER SET ASCII;
  function FREE(A_KEY CHAR(36) CHARACTER SET ASCII)
    returns BOOLEAN;

  function GET_S(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE_IF_NULL VARCHAR(8191) CHARACTER SET UTF8 DEFAULT NULL)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function GET_I(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE_IF_NULL INTEGER DEFAULT NULL)
    returns INTEGER;
  function GET_L(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE_IF_NULL BIGINT DEFAULT NULL)
    returns BIGINT;
  function GET_F(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE_IF_NULL DOUBLE PRECISION DEFAULT NULL)
    returns DOUBLE PRECISION;
  function GET_B(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE_IF_NULL BOOLEAN DEFAULT NULL)
    returns BOOLEAN;
  function GET_D(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE_IF_NULL TIMESTAMP DEFAULT NULL)
    returns TIMESTAMP;
  function GET(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function GET_TYPE(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(32) CHARACTER SET UTF8;
  function EXIST(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns BOOLEAN;
  function IS_NULL(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns BOOLEAN;
  function LEN(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns INTEGER;
  function INDEXOF(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns INTEGER;
  function NAMEOF(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER)
    returns VARCHAR(8191) CHARACTER SET UTF8;

  function GET_AT_S(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER,
      A_VALUE_IF_NULL VARCHAR(8191) CHARACTER SET UTF8 DEFAULT NULL)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function GET_AT_I(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER,
      A_VALUE_IF_NULL INTEGER DEFAULT NULL)
    returns INTEGER;
  function GET_AT_L(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER,
      A_VALUE_IF_NULL BIGINT DEFAULT NULL)
    returns BIGINT;
  function GET_AT_F(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER,
      A_VALUE_IF_NULL DOUBLE PRECISION DEFAULT NULL)
    returns DOUBLE PRECISION;
  function GET_AT_B(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER,
      A_VALUE_IF_NULL BOOLEAN DEFAULT NULL)
    returns BOOLEAN;
  function GET_AT_D(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER,
      A_VALUE_IF_NULL TIMESTAMP DEFAULT NULL)
    returns TIMESTAMP;
  function GET_AT(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function GET_AT_TYPE(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER)
    returns VARCHAR(32) CHARACTER SET UTF8;

  function SET_S(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function SET_I(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE INTEGER)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function SET_L(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE BIGINT)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function SET_F(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE DOUBLE PRECISION)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function SET_B(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE BOOLEAN)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function SET_D(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE TIMESTAMP)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function SET_NULL(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function SET_J(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_JSON_VALUE VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function REMOVE(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function CLEAR(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function ASSIGN(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_SOURCE VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function DELETEOF(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function SET_LEN(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_COUNT INTEGER)
    returns VARCHAR(8191) CHARACTER SET UTF8;

  function SET_AT_S(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER,
      A_VALUE VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function SET_AT_I(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER, A_VALUE INTEGER)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function SET_AT_L(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER, A_VALUE BIGINT)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function SET_AT_F(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER, A_VALUE DOUBLE PRECISION)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function SET_AT_B(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER, A_VALUE BOOLEAN)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function SET_AT_D(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER, A_VALUE TIMESTAMP)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function SET_AT_NULL(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function SET_AT_J(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER,
      A_JSON_VALUE VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function REMOVE_AT(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER)
    returns VARCHAR(8191) CHARACTER SET UTF8;

  function ADD_S(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function ADD_I(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE INTEGER)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function ADD_L(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE BIGINT)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function ADD_F(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE DOUBLE PRECISION)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function ADD_B(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE BOOLEAN)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function ADD_D(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE TIMESTAMP)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function ADD_A(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function ADD_O(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function ADD_J(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_JSON_VALUE VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8;

  function INS_S(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER, A_VALUE VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function INS_I(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER, A_VALUE INTEGER)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function INS_L(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER, A_VALUE BIGINT)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function INS_F(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER, A_VALUE DOUBLE PRECISION)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function INS_B(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER, A_VALUE BOOLEAN)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function INS_D(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER, A_VALUE TIMESTAMP)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function INS_A(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function INS_O(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function INS(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER, A_JSON_VALUE VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8;

  procedure NODES(
      A_JSON      VARCHAR(8191) CHARACTER SET UTF8,
      A_PATH      VARCHAR(8191) CHARACTER SET UTF8,
      A_FULL_PATH BOOLEAN DEFAULT TRUE)
    returns (
      ABS_INDEX INTEGER,
      LOC_INDEX INTEGER,
      NAME      VARCHAR(8191) CHARACTER SET UTF8,
      PATH      VARCHAR(8191) CHARACTER SET UTF8,
      TYP       VARCHAR(32) CHARACTER SET UTF8,
      VAL       VARCHAR(8191) CHARACTER SET UTF8
    );

  procedure ITEMS(
      A_JSON VARCHAR(8191) CHARACTER SET UTF8,
      A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns (
      LOC_INDEX INTEGER,
      NAME      VARCHAR(8191) CHARACTER SET UTF8,
      TYP       VARCHAR(32) CHARACTER SET UTF8,
      VAL       VARCHAR(8191) CHARACTER SET UTF8
    );
end^

recreate package body SJSON
as
begin
  function NEW_OBJECT() returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_NewObject' engine udr;
  function NEW_ARRAY() returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_NewArray' engine udr;
  function NEW_OBJKEY() returns CHAR(36) CHARACTER SET ASCII
    external name 'PxrJSON!SJson_NewObjKey' engine udr;
  function NEW_ARRKEY() returns CHAR(36) CHARACTER SET ASCII
    external name 'PxrJSON!SJson_NewArrKey' engine udr;
  function TOJSON(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_COMPACT SMALLINT)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_ToJson' engine udr;
  function KEYSIZE(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_COMPACT SMALLINT)
    returns INTEGER
    external name 'PxrJSON!SJson_KeySize' engine udr;
  function PARSE(A_JSON VARCHAR(8191) CHARACTER SET UTF8)
    returns CHAR(36) CHARACTER SET ASCII
    external name 'PxrJSON!SJson_Parse' engine udr;
  function CLONE(A_JSON VARCHAR(8191) CHARACTER SET UTF8)
    returns CHAR(36) CHARACTER SET ASCII
    external name 'PxrJSON!SJson_Clone' engine udr;
  function EXTRACTJSON(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_ExtractJson' engine udr;
  function EXTRACTKEY(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns CHAR(36) CHARACTER SET ASCII
    external name 'PxrJSON!SJson_ExtractKey' engine udr;
  function FREE(A_KEY CHAR(36) CHARACTER SET ASCII)
    returns BOOLEAN
    external name 'PxrJSON!SJson_Free' engine udr;

  function GET_S(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE_IF_NULL VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_GetS' engine udr;
  function GET_I(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE_IF_NULL INTEGER)
    returns INTEGER
    external name 'PxrJSON!SJson_GetI' engine udr;
  function GET_L(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE_IF_NULL BIGINT)
    returns BIGINT
    external name 'PxrJSON!SJson_GetL' engine udr;
  function GET_F(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE_IF_NULL DOUBLE PRECISION)
    returns DOUBLE PRECISION
    external name 'PxrJSON!SJson_GetF' engine udr;
  function GET_B(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE_IF_NULL BOOLEAN)
    returns BOOLEAN
    external name 'PxrJSON!SJson_GetB' engine udr;
  function GET_D(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE_IF_NULL TIMESTAMP)
    returns TIMESTAMP
    external name 'PxrJSON!SJson_GetD' engine udr;
  function GET(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_Get' engine udr;
  function GET_TYPE(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(32) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_GetType' engine udr;
  function EXIST(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns BOOLEAN
    external name 'PxrJSON!SJson_Exists' engine udr;
  function IS_NULL(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns BOOLEAN
    external name 'PxrJSON!SJson_IsNull' engine udr;
  function LEN(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns INTEGER
    external name 'PxrJSON!SJson_Count' engine udr;
  function INDEXOF(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns INTEGER
    external name 'PxrJSON!SJson_IndexOf' engine udr;
  function NAMEOF(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_NameOf' engine udr;

  function GET_AT_S(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER,
      A_VALUE_IF_NULL VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_GetAtS' engine udr;
  function GET_AT_I(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER,
      A_VALUE_IF_NULL INTEGER)
    returns INTEGER
    external name 'PxrJSON!SJson_GetAtI' engine udr;
  function GET_AT_L(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER,
      A_VALUE_IF_NULL BIGINT)
    returns BIGINT
    external name 'PxrJSON!SJson_GetAtL' engine udr;
  function GET_AT_F(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER,
      A_VALUE_IF_NULL DOUBLE PRECISION)
    returns DOUBLE PRECISION
    external name 'PxrJSON!SJson_GetAtF' engine udr;
  function GET_AT_B(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER,
      A_VALUE_IF_NULL BOOLEAN)
    returns BOOLEAN
    external name 'PxrJSON!SJson_GetAtB' engine udr;
  function GET_AT_D(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER,
      A_VALUE_IF_NULL TIMESTAMP)
    returns TIMESTAMP
    external name 'PxrJSON!SJson_GetAtD' engine udr;
  function GET_AT(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_GetAt' engine udr;
  function GET_AT_TYPE(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER)
    returns VARCHAR(32) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_GetAtType' engine udr;

  function SET_S(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_SetS' engine udr;
  function SET_I(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE INTEGER)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_SetI' engine udr;
  function SET_L(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE BIGINT)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_SetL' engine udr;
  function SET_F(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE DOUBLE PRECISION)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_SetF' engine udr;
  function SET_B(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE BOOLEAN)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_SetB' engine udr;
  function SET_D(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE TIMESTAMP)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_SetD' engine udr;
  function SET_NULL(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_SetNull' engine udr;
  function SET_J(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_JSON_VALUE VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_Set' engine udr;
  function REMOVE(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_Remove' engine udr;
  function CLEAR(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_Clear' engine udr;
  function ASSIGN(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_SOURCE VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_Assign' engine udr;
  function DELETEOF(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_DeleteOf' engine udr;
  function SET_LEN(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_COUNT INTEGER)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_SetLen' engine udr;

  function SET_AT_S(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER,
      A_VALUE VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_SetAtS' engine udr;
  function SET_AT_I(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER, A_VALUE INTEGER)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_SetAtI' engine udr;
  function SET_AT_L(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER, A_VALUE BIGINT)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_SetAtL' engine udr;
  function SET_AT_F(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER, A_VALUE DOUBLE PRECISION)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_SetAtF' engine udr;
  function SET_AT_B(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER, A_VALUE BOOLEAN)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_SetAtB' engine udr;
  function SET_AT_D(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER, A_VALUE TIMESTAMP)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_SetAtD' engine udr;
  function SET_AT_NULL(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_SetAtNull' engine udr;
  function SET_AT_J(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER,
      A_JSON_VALUE VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_SetAtJ' engine udr;
  function REMOVE_AT(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_INDEX INTEGER)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_RemoveAt' engine udr;

  function ADD_S(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_AddS' engine udr;
  function ADD_I(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE INTEGER)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_AddI' engine udr;
  function ADD_L(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE BIGINT)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_AddL' engine udr;
  function ADD_F(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE DOUBLE PRECISION)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_AddF' engine udr;
  function ADD_B(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE BOOLEAN)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_AddB' engine udr;
  function ADD_D(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE TIMESTAMP)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_AddD' engine udr;
  function ADD_A(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_AddA' engine udr;
  function ADD_O(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_AddO' engine udr;
  function ADD_J(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_JSON_VALUE VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_Add' engine udr;

  function INS_S(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER, A_VALUE VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_InsS' engine udr;
  function INS_I(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER, A_VALUE INTEGER)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_InsI' engine udr;
  function INS_L(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER, A_VALUE BIGINT)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_InsL' engine udr;
  function INS_F(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER, A_VALUE DOUBLE PRECISION)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_InsF' engine udr;
  function INS_B(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER, A_VALUE BOOLEAN)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_InsB' engine udr;
  function INS_D(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER, A_VALUE TIMESTAMP)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_InsD' engine udr;
  function INS_A(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_InsA' engine udr;
  function INS_O(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_InsO' engine udr;
  function INS(A_JSON VARCHAR(8191) CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER, A_JSON_VALUE VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!SJson_Ins' engine udr;

  procedure NODES(
      A_JSON      VARCHAR(8191) CHARACTER SET UTF8,
      A_PATH      VARCHAR(8191) CHARACTER SET UTF8,
      A_FULL_PATH BOOLEAN)
    returns (
      ABS_INDEX INTEGER,
      LOC_INDEX INTEGER,
      NAME      VARCHAR(8191) CHARACTER SET UTF8,
      PATH      VARCHAR(8191) CHARACTER SET UTF8,
      TYP       VARCHAR(32) CHARACTER SET UTF8,
      VAL       VARCHAR(8191) CHARACTER SET UTF8
    )
    external name 'PxrJSON!SJson_Nodes' engine udr;

  procedure ITEMS(
      A_JSON VARCHAR(8191) CHARACTER SET UTF8,
      A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns (
      LOC_INDEX INTEGER,
      NAME      VARCHAR(8191) CHARACTER SET UTF8,
      TYP       VARCHAR(32) CHARACTER SET UTF8,
      VAL       VARCHAR(8191) CHARACTER SET UTF8
    )
    external name 'PxrJSON!SJson_Items' engine udr;
end^

create or alter package BJSON
as
begin
  function NEW_OBJECT() returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function NEW_ARRAY() returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function NEW_OBJKEY() returns CHAR(36) CHARACTER SET ASCII;
  function NEW_ARRKEY() returns CHAR(36) CHARACTER SET ASCII;
  function TOJSON(
      A_JSON    BLOB SUB_TYPE TEXT CHARACTER SET UTF8,
      A_COMPACT SMALLINT DEFAULT 1)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function KEYSIZE(
      A_JSON    BLOB SUB_TYPE TEXT CHARACTER SET UTF8,
      A_COMPACT SMALLINT DEFAULT 1)
    returns INTEGER;
  function PARSE(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8)
    returns CHAR(36) CHARACTER SET ASCII;
  function CLONE(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8)
    returns CHAR(36) CHARACTER SET ASCII;
  function EXTRACTJSON(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function EXTRACTKEY(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns CHAR(36) CHARACTER SET ASCII;
  function FREE(A_KEY CHAR(36) CHARACTER SET ASCII)
    returns BOOLEAN;

  function GET_S(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE_IF_NULL VARCHAR(8191) CHARACTER SET UTF8 DEFAULT NULL)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function GET_I(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE_IF_NULL INTEGER DEFAULT NULL)
    returns INTEGER;
  function GET_L(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE_IF_NULL BIGINT DEFAULT NULL)
    returns BIGINT;
  function GET_F(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE_IF_NULL DOUBLE PRECISION DEFAULT NULL)
    returns DOUBLE PRECISION;
  function GET_B(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE_IF_NULL BOOLEAN DEFAULT NULL)
    returns BOOLEAN;
  function GET_D(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE_IF_NULL TIMESTAMP DEFAULT NULL)
    returns TIMESTAMP;
  function GET(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function GET_TYPE(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(32) CHARACTER SET UTF8;
  function EXIST(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns BOOLEAN;
  function IS_NULL(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns BOOLEAN;
  function LEN(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns INTEGER;
  function INDEXOF(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns INTEGER;
  function NAMEOF(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER)
    returns VARCHAR(8191) CHARACTER SET UTF8;

  function GET_AT_S(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER,
      A_VALUE_IF_NULL VARCHAR(8191) CHARACTER SET UTF8 DEFAULT NULL)
    returns VARCHAR(8191) CHARACTER SET UTF8;
  function GET_AT_I(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER,
      A_VALUE_IF_NULL INTEGER DEFAULT NULL)
    returns INTEGER;
  function GET_AT_L(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER,
      A_VALUE_IF_NULL BIGINT DEFAULT NULL)
    returns BIGINT;
  function GET_AT_F(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER,
      A_VALUE_IF_NULL DOUBLE PRECISION DEFAULT NULL)
    returns DOUBLE PRECISION;
  function GET_AT_B(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER,
      A_VALUE_IF_NULL BOOLEAN DEFAULT NULL)
    returns BOOLEAN;
  function GET_AT_D(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER,
      A_VALUE_IF_NULL TIMESTAMP DEFAULT NULL)
    returns TIMESTAMP;
  function GET_AT(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function GET_AT_TYPE(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER)
    returns VARCHAR(32) CHARACTER SET UTF8;

  function SET_S(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE VARCHAR(8191) CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function SET_I(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE INTEGER)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function SET_L(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE BIGINT)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function SET_F(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE DOUBLE PRECISION)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function SET_B(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE BOOLEAN)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function SET_D(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE TIMESTAMP)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function SET_NULL(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function SET_J(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_JSON_VALUE BLOB SUB_TYPE TEXT CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function REMOVE(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function CLEAR(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function ASSIGN(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_SOURCE BLOB SUB_TYPE TEXT CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function DELETEOF(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function SET_LEN(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_COUNT INTEGER)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;

  function SET_AT_S(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER,
      A_VALUE VARCHAR(8191) CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function SET_AT_I(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER, A_VALUE INTEGER)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function SET_AT_L(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER, A_VALUE BIGINT)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function SET_AT_F(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER, A_VALUE DOUBLE PRECISION)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function SET_AT_B(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER, A_VALUE BOOLEAN)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function SET_AT_D(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER, A_VALUE TIMESTAMP)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function SET_AT_NULL(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function SET_AT_J(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER,
      A_JSON_VALUE BLOB SUB_TYPE TEXT CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function REMOVE_AT(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;

  function ADD_S(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE VARCHAR(8191) CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function ADD_I(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE INTEGER)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function ADD_L(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE BIGINT)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function ADD_F(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE DOUBLE PRECISION)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function ADD_B(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE BOOLEAN)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function ADD_D(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE TIMESTAMP)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function ADD_A(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function ADD_O(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function ADD_J(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_JSON_VALUE BLOB SUB_TYPE TEXT CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;

  function INS_S(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER, A_VALUE VARCHAR(8191) CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function INS_I(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER, A_VALUE INTEGER)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function INS_L(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER, A_VALUE BIGINT)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function INS_F(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER, A_VALUE DOUBLE PRECISION)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function INS_B(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER, A_VALUE BOOLEAN)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function INS_D(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER, A_VALUE TIMESTAMP)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function INS_A(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function INS_O(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
  function INS(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER, A_JSON_VALUE BLOB SUB_TYPE TEXT CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8;

  procedure NODES(
      A_JSON      BLOB SUB_TYPE TEXT CHARACTER SET UTF8,
      A_PATH      VARCHAR(8191) CHARACTER SET UTF8,
      A_FULL_PATH BOOLEAN DEFAULT TRUE)
    returns (
      ABS_INDEX INTEGER,
      LOC_INDEX INTEGER,
      NAME      VARCHAR(8191) CHARACTER SET UTF8,
      PATH      VARCHAR(8191) CHARACTER SET UTF8,
      TYP       VARCHAR(32) CHARACTER SET UTF8,
      VAL       VARCHAR(8191) CHARACTER SET UTF8
    );

  procedure ITEMS(
      A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8,
      A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns (
      LOC_INDEX INTEGER,
      NAME      VARCHAR(8191) CHARACTER SET UTF8,
      TYP       VARCHAR(32) CHARACTER SET UTF8,
      VAL       VARCHAR(8191) CHARACTER SET UTF8
    );
end^

recreate package body BJSON
as
begin
  function NEW_OBJECT() returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_NewObject' engine udr;
  function NEW_ARRAY() returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_NewArray' engine udr;
  function NEW_OBJKEY() returns CHAR(36) CHARACTER SET ASCII
    external name 'PxrJSON!BJson_NewObjKey' engine udr;
  function NEW_ARRKEY() returns CHAR(36) CHARACTER SET ASCII
    external name 'PxrJSON!BJson_NewArrKey' engine udr;
  function TOJSON(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_COMPACT SMALLINT)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_ToJson' engine udr;
  function KEYSIZE(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_COMPACT SMALLINT)
    returns INTEGER
    external name 'PxrJSON!BJson_KeySize' engine udr;
  function PARSE(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8)
    returns CHAR(36) CHARACTER SET ASCII
    external name 'PxrJSON!BJson_Parse' engine udr;
  function CLONE(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8)
    returns CHAR(36) CHARACTER SET ASCII
    external name 'PxrJSON!BJson_Clone' engine udr;
  function EXTRACTJSON(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_ExtractJson' engine udr;
  function EXTRACTKEY(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns CHAR(36) CHARACTER SET ASCII
    external name 'PxrJSON!BJson_ExtractKey' engine udr;
  function FREE(A_KEY CHAR(36) CHARACTER SET ASCII)
    returns BOOLEAN
    external name 'PxrJSON!BJson_Free' engine udr;

  function GET_S(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE_IF_NULL VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!BJson_GetS' engine udr;
  function GET_I(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE_IF_NULL INTEGER)
    returns INTEGER
    external name 'PxrJSON!BJson_GetI' engine udr;
  function GET_L(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE_IF_NULL BIGINT)
    returns BIGINT
    external name 'PxrJSON!BJson_GetL' engine udr;
  function GET_F(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE_IF_NULL DOUBLE PRECISION)
    returns DOUBLE PRECISION
    external name 'PxrJSON!BJson_GetF' engine udr;
  function GET_B(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE_IF_NULL BOOLEAN)
    returns BOOLEAN
    external name 'PxrJSON!BJson_GetB' engine udr;
  function GET_D(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE_IF_NULL TIMESTAMP)
    returns TIMESTAMP
    external name 'PxrJSON!BJson_GetD' engine udr;
  function GET(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_Get' engine udr;
  function GET_TYPE(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(32) CHARACTER SET UTF8
    external name 'PxrJSON!BJson_GetType' engine udr;
  function EXIST(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns BOOLEAN
    external name 'PxrJSON!BJson_Exists' engine udr;
  function IS_NULL(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns BOOLEAN
    external name 'PxrJSON!BJson_IsNull' engine udr;
  function LEN(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns INTEGER
    external name 'PxrJSON!BJson_Count' engine udr;
  function INDEXOF(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns INTEGER
    external name 'PxrJSON!BJson_IndexOf' engine udr;
  function NAMEOF(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!BJson_NameOf' engine udr;

  function GET_AT_S(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER,
      A_VALUE_IF_NULL VARCHAR(8191) CHARACTER SET UTF8)
    returns VARCHAR(8191) CHARACTER SET UTF8
    external name 'PxrJSON!BJson_GetAtS' engine udr;
  function GET_AT_I(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER,
      A_VALUE_IF_NULL INTEGER)
    returns INTEGER
    external name 'PxrJSON!BJson_GetAtI' engine udr;
  function GET_AT_L(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER,
      A_VALUE_IF_NULL BIGINT)
    returns BIGINT
    external name 'PxrJSON!BJson_GetAtL' engine udr;
  function GET_AT_F(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER,
      A_VALUE_IF_NULL DOUBLE PRECISION)
    returns DOUBLE PRECISION
    external name 'PxrJSON!BJson_GetAtF' engine udr;
  function GET_AT_B(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER,
      A_VALUE_IF_NULL BOOLEAN)
    returns BOOLEAN
    external name 'PxrJSON!BJson_GetAtB' engine udr;
  function GET_AT_D(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER,
      A_VALUE_IF_NULL TIMESTAMP)
    returns TIMESTAMP
    external name 'PxrJSON!BJson_GetAtD' engine udr;
  function GET_AT(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_GetAt' engine udr;
  function GET_AT_TYPE(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER)
    returns VARCHAR(32) CHARACTER SET UTF8
    external name 'PxrJSON!BJson_GetAtType' engine udr;

  function SET_S(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE VARCHAR(8191) CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_SetS' engine udr;
  function SET_I(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE INTEGER)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_SetI' engine udr;
  function SET_L(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE BIGINT)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_SetL' engine udr;
  function SET_F(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE DOUBLE PRECISION)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_SetF' engine udr;
  function SET_B(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE BOOLEAN)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_SetB' engine udr;
  function SET_D(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE TIMESTAMP)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_SetD' engine udr;
  function SET_NULL(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_SetNull' engine udr;
  function SET_J(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_JSON_VALUE BLOB SUB_TYPE TEXT CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_Set' engine udr;
  function REMOVE(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_Remove' engine udr;
  function CLEAR(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_Clear' engine udr;
  function ASSIGN(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_SOURCE BLOB SUB_TYPE TEXT CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_Assign' engine udr;
  function DELETEOF(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_DeleteOf' engine udr;
  function SET_LEN(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_COUNT INTEGER)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_SetLen' engine udr;

  function SET_AT_S(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER,
      A_VALUE VARCHAR(8191) CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_SetAtS' engine udr;
  function SET_AT_I(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER, A_VALUE INTEGER)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_SetAtI' engine udr;
  function SET_AT_L(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER, A_VALUE BIGINT)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_SetAtL' engine udr;
  function SET_AT_F(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER, A_VALUE DOUBLE PRECISION)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_SetAtF' engine udr;
  function SET_AT_B(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER, A_VALUE BOOLEAN)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_SetAtB' engine udr;
  function SET_AT_D(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER, A_VALUE TIMESTAMP)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_SetAtD' engine udr;
  function SET_AT_NULL(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_SetAtNull' engine udr;
  function SET_AT_J(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER,
      A_JSON_VALUE BLOB SUB_TYPE TEXT CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_SetAtJ' engine udr;
  function REMOVE_AT(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_INDEX INTEGER)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_RemoveAt' engine udr;

  function ADD_S(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_VALUE VARCHAR(8191) CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_AddS' engine udr;
  function ADD_I(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE INTEGER)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_AddI' engine udr;
  function ADD_L(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE BIGINT)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_AddL' engine udr;
  function ADD_F(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE DOUBLE PRECISION)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_AddF' engine udr;
  function ADD_B(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE BOOLEAN)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_AddB' engine udr;
  function ADD_D(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8, A_VALUE TIMESTAMP)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_AddD' engine udr;
  function ADD_A(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_AddA' engine udr;
  function ADD_O(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_AddO' engine udr;
  function ADD_J(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_JSON_VALUE BLOB SUB_TYPE TEXT CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_Add' engine udr;

  function INS_S(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER, A_VALUE VARCHAR(8191) CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_InsS' engine udr;
  function INS_I(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER, A_VALUE INTEGER)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_InsI' engine udr;
  function INS_L(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER, A_VALUE BIGINT)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_InsL' engine udr;
  function INS_F(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER, A_VALUE DOUBLE PRECISION)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_InsF' engine udr;
  function INS_B(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER, A_VALUE BOOLEAN)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_InsB' engine udr;
  function INS_D(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER, A_VALUE TIMESTAMP)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_InsD' engine udr;
  function INS_A(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_InsA' engine udr;
  function INS_O(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_InsO' engine udr;
  function INS(A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8, A_PATH VARCHAR(8191) CHARACTER SET UTF8,
      A_INDEX INTEGER, A_JSON_VALUE BLOB SUB_TYPE TEXT CHARACTER SET UTF8)
    returns BLOB SUB_TYPE TEXT CHARACTER SET UTF8
    external name 'PxrJSON!BJson_Ins' engine udr;

  procedure NODES(
      A_JSON      BLOB SUB_TYPE TEXT CHARACTER SET UTF8,
      A_PATH      VARCHAR(8191) CHARACTER SET UTF8,
      A_FULL_PATH BOOLEAN)
    returns (
      ABS_INDEX INTEGER,
      LOC_INDEX INTEGER,
      NAME      VARCHAR(8191) CHARACTER SET UTF8,
      PATH      VARCHAR(8191) CHARACTER SET UTF8,
      TYP       VARCHAR(32) CHARACTER SET UTF8,
      VAL       VARCHAR(8191) CHARACTER SET UTF8
    )
    external name 'PxrJSON!BJson_Nodes' engine udr;

  procedure ITEMS(
      A_JSON BLOB SUB_TYPE TEXT CHARACTER SET UTF8,
      A_PATH VARCHAR(8191) CHARACTER SET UTF8)
    returns (
      LOC_INDEX INTEGER,
      NAME      VARCHAR(8191) CHARACTER SET UTF8,
      TYP       VARCHAR(32) CHARACTER SET UTF8,
      VAL       VARCHAR(8191) CHARACTER SET UTF8
    )
    external name 'PxrJSON!BJson_Items' engine udr;
end^

-- IBExpert Code Insight: function name hint comes from COMMENT ON (RDB$DESCRIPTION).
-- After "(" you see parameters; if a parameter has no comment, enable
-- Options → Editor Options → Code Insight → Show parent object description.

execute block
as
  declare pkg varchar(31);
  declare stmt varchar(500);
begin
  execute statement
    'comment on package SJSON is ''JSON VARCHAR(8191). Same names as BJSON. Document is text or a PARSE/CLONE key.''';
  execute statement
    'comment on package BJSON is ''JSON BLOB TEXT. Same names as SJSON. Document is text or a PARSE/CLONE key.''';

  for select 'SJSON' from rdb$database
      union all
      select 'BJSON' from rdb$database
      into :pkg
  do
  begin
    stmt = 'comment on function ' || pkg || '.NEW_OBJECT is ''Empty object {}, JSON text (does not create a key)''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.NEW_ARRAY is ''Empty array [], JSON text (does not create a key)''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.NEW_OBJKEY is ''Empty object in the session cache; returns CHAR(36) key''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.NEW_ARRKEY is ''Empty array in the session cache; returns CHAR(36) key''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.TOJSON is ''Serialize tree (key or text); compact 1=one line, 0=pretty''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.KEYSIZE is ''Length of ToJSON text in characters (no document round-trip for a key)''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.PARSE is ''Parse JSON text into the cache; returns a key. A key as input is an error''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.CLONE is ''Copy of the tree; always a new key (input may be text or a key)''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.EXTRACTJSON is ''Cut node at path; returns it as JSON text. Key input mutates the parent in place''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.EXTRACTKEY is ''Cut object/array at path; returns a new key. Key input mutates the parent in place''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.FREE is ''Drop the tree for this key. Repeat -> FALSE; SQL NULL -> NULL''';
    execute statement stmt;

    stmt = 'comment on function ' || pkg || '.GET_S is ''String at path. Missing / JSON null -> SQL NULL or value_if_null''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.GET_I is ''INTEGER at path. Missing / JSON null -> SQL NULL or value_if_null''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.GET_L is ''BIGINT at path. Missing / JSON null -> SQL NULL or value_if_null''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.GET_F is ''DOUBLE PRECISION at path. Missing / JSON null -> SQL NULL or value_if_null''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.GET_B is ''BOOLEAN at path. Missing / JSON null -> SQL NULL or value_if_null''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.GET_D is ''TIMESTAMP at path (JDO .D). Missing / JSON null -> SQL NULL or value_if_null''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.GET is ''Node as JSON text: object, array, or scalar''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.GET_TYPE is ''Node type: null, String, Integer, Long, Float, Bool, Array, Object, DateTime''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.EXIST is ''Path exists? JSON null -> TRUE. Missing path -> FALSE''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.IS_NULL is ''Path holds JSON null (not a missing field)''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.LEN is ''Object key count or array length. Scalar / missing path -> NULL''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.INDEXOF is ''Sibling index of the last path segment. Missing -> NULL''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.NAMEOF is ''i-th object key name at path. Missing / out of range -> NULL''';
    execute statement stmt;

    stmt = 'comment on function ' || pkg || '.GET_AT_S is ''String of an array element (json is the array itself, not a path)''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.GET_AT_I is ''INTEGER of an array element''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.GET_AT_L is ''BIGINT of an array element''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.GET_AT_F is ''DOUBLE PRECISION of an array element''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.GET_AT_B is ''BOOLEAN of an array element''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.GET_AT_D is ''TIMESTAMP of an array element''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.GET_AT is ''Array element as JSON''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.GET_AT_TYPE is ''Type of an array element''';
    execute statement stmt;

    stmt = 'comment on function ' || pkg || '.SET_S is ''Write a string; SQL NULL -> JSON null. Returns text or the same key''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.SET_I is ''Write INTEGER; SQL NULL -> JSON null''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.SET_L is ''Write BIGINT; SQL NULL -> JSON null''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.SET_F is ''Write DOUBLE PRECISION; SQL NULL -> JSON null''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.SET_B is ''Write BOOLEAN; SQL NULL -> JSON null''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.SET_D is ''Write TIMESTAMP (JDO .D); SQL NULL -> JSON null''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.SET_NULL is ''Write JSON null at path''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.SET_J is ''Replace node: JSON text or key (tree is copied)''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.REMOVE is ''Delete object field or array element at path''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.CLEAR is ''Empty object/array in place. Empty path = root''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.ASSIGN is ''Copy source contents (text or key). Empty path = root''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.DELETEOF is ''Delete i-th object field (arrays: REMOVE_AT)''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.SET_LEN is ''Set array length (.Count), n>=0''';
    execute statement stmt;

    stmt = 'comment on function ' || pkg || '.SET_AT_S is ''Write string into array element; SQL NULL -> JSON null''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.SET_AT_I is ''Write INTEGER into array element''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.SET_AT_L is ''Write BIGINT into array element''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.SET_AT_F is ''Write DOUBLE PRECISION into array element''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.SET_AT_B is ''Write BOOLEAN into array element''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.SET_AT_D is ''Write TIMESTAMP into array element''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.SET_AT_NULL is ''JSON null in array cell''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.SET_AT_J is ''Replace array cell with a node''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.REMOVE_AT is ''Delete array element by index''';
    execute statement stmt;

    stmt = 'comment on function ' || pkg || '.ADD_S is ''Append string to array at path (array is created if missing)''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.ADD_I is ''Append INTEGER to array''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.ADD_L is ''Append BIGINT to array''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.ADD_F is ''Append DOUBLE PRECISION to array''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.ADD_B is ''Append BOOLEAN to array''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.ADD_D is ''Append TIMESTAMP to array''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.ADD_A is ''Append empty array []''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.ADD_O is ''Append empty object {}''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.ADD_J is ''Append node (JSON text or key) to array''';
    execute statement stmt;

    stmt = 'comment on function ' || pkg || '.INS_S is ''Insert string into array at index (0..LEN)''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.INS_I is ''Insert INTEGER into array''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.INS_L is ''Insert BIGINT into array''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.INS_F is ''Insert DOUBLE PRECISION into array''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.INS_B is ''Insert BOOLEAN into array''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.INS_D is ''Insert TIMESTAMP into array''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.INS_A is ''Insert empty array [] at index''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.INS_O is ''Insert empty object {} at index''';
    execute statement stmt;
    stmt = 'comment on function ' || pkg || '.INS is ''Insert node (JSON text or key) into array''';
    execute statement stmt;

    stmt = 'comment on procedure ' || pkg || '.NODES is ''Depth-first walk: ABS_INDEX, LOC_INDEX, NAME, PATH, TYP, VAL''';
    execute statement stmt;
    stmt = 'comment on procedure ' || pkg || '.ITEMS is ''One array level: a row per field of each element''';
    execute statement stmt;
  end
end^

set term ; ^

commit;
